### ISSUE TITLE
Query - boot on real hardware

### ISSUE THREAD

**Issue by mschwartz** [ReturnInfinity/BareMetal#82]
I'm curious if this runs on real hardware?

It seems like to boot off a USB drive to install to hard drive (or SSD), second and third stage loading would require a USB driver.

Just curious as to how you would approach this, or if I'm mistaken...

I presume you can't load from USB using ATA drivers.

**Comment by IanSeyler** [comment]
Yes - this will boot on real hardware. Booting from USB gets you into the CLI but you are unable to load programs from the USB driver since there is no driver.

NVMe, AHCI, ATA, and Virtio-Block are the best boot methods.

For my test system I boot the kernel up via a USB drive (for fast changes) and a AHCI SSD contains the programs. I can also boot directly from the SSD.
